// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   audio/src/AudParameter.h
// Generated by format-carbon carbon-class --emit. Verify against audio/AudParameter.json.
import { io, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** AudParameter (audio) - generated from schema shapeHash daad2621.... */
@type.define({ className: "AudParameter", family: "audio" })
export class AudParameter extends CjsModel
{

  /** m_name (std::wstring) [READWRITE] */
  @io.readwrite
  @type.string
  name = "";

  /** m_value (float) [READWRITE, NOTIFY] */
  @io.notify
  @io.readwrite
  @type.float32
  value = 0;

}
