// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   audio/src/AudUIPlayer.h
// Generated by format-carbon carbon-class --emit. Verify against audio/AudUIPlayer.json.
import { carbon, impl, io, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** AudUIPlayer (audio) - generated from schema shapeHash 81f49333.... */
@type.define({ className: "AudUIPlayer", family: "audio" })
export class AudUIPlayer extends CjsModel
{

  /** m_callback (BlueScriptCallback) [READWRITE] */
  @io.readwrite
  @type.rawStruct("BlueScriptCallback")
  eventSenderCallback = null;

  /** Carbon method GetEventPlayPosition (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  GetEventPlayPosition(...args)
  {
    throw new Error("AudUIPlayer.GetEventPlayPosition is not implemented in CarbonEngineJS.");
  }

  /** Carbon method PostDialogueEvent (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  PostDialogueEvent(...args)
  {
    throw new Error("AudUIPlayer.PostDialogueEvent is not implemented in CarbonEngineJS.");
  }

  /** Carbon method SendEventWithCallback (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.notImplemented
  SendEventWithCallback(...args)
  {
    throw new Error("AudUIPlayer.SendEventWithCallback is not implemented in CarbonEngineJS.");
  }

}
